### PR TITLE
Set DefaultMatrixAutoUpdate false and fix rig problem. 

### PR DESCRIPTION
**Pull request by gonnavis**
To match this PR in app: https://github.com/webaverse/app/pull/2063/

### CODE REVIEW

**Review by avaer — APPROVED** [review]

**Comment by avaer** [comment]
This isn't a huge deal, but this is not a good PR title. It is not setting `DefaultMatrixAutoUpdate` false in this PR, but now it's in the `git log` history and will confuse future devs.

image

**Comment by avaer** [comment]
I'm going to revert this since it was premature.

We might not be doing this update solution at all, if it doesn't prove performant. We should only do this PR once the performance improves.

**Comment by avaer** [comment]
https://github.com/webaverse/totum/commit/2f8b8c3bec46f7e28cf2e4ea69247ba8a85f91bc

**Comment by gonnavis** [comment]
> This isn't a huge deal, but this is not a good PR title. It is not setting `DefaultMatrixAutoUpdate` false in this PR, but now it's in the `git log` history and will confuse future devs.

Oh, my initial idea was to match the PR title of the app repo. 
Next time I encounter this situation, I will change the naming method.


> I'm going to revert this since it was premature.
We might not be doing this update solution at all, if it doesn't prove performant. We should only do this PR once the performance improves.

Get it.

**Pull request merged**
