### PR TITLE
remove unneeded unskin code

### LINKED ISSUE #71: remove unskinned vrms from totum
the logic for unskinning and reapplying skins to vrms is no longer needed, so it's being removed

### PR DESCRIPTION
**Pull request by 0reo**
closes #71 .  Requires removing the calls to setSkinning in webaverse app, related PR incoming.

### CODE REVIEW

**Comment by avaer** [comment]
Is there any chance this causes per-frame bones updates for all avatars, where previously it only applied to worn ones?

**Review by avaer — APPROVED** [review]

**Comment by avaer** [comment]
Looks good provided that it does not introduce new performance problems (see the above concern).

**Comment by 0reo** [comment]
> Is there any chance this causes per-frame bones updates for all avatars, where previously it only applied to worn ones, causing significant performance degradation with non-worn avatars?
> 
> https://github.com/webaverse/totum/pull/72/files#diff-cfee11949007510c60d7d3ed4527b937a41ea1f55995dd1b341f8c01d36a32feL79

We can set `matrixAutoUpdate = false` on the bones of any vrm we don't want to update, and toggle it when it gets worn.  Currently the Avatar class seems to be in charge of handling bone setup/logic, so I could add the changes there.  Or I could have the bones set to `matrixAutoUpdate = false` by default in the vrm template, and add a function to manually trigger updates, which could be called when an avatar is worn/unworn, or as needed.

**Comment by avaer** [comment]
☝️ Isn't that the exact same thing as the "unskinned" vs "skinned" VRMs which are being removed here?

Except instead of there being a clean separation like there is with skinned vs unskinned, it would be a single avatar that is being hacked/unhacked to behave differently at different times?

**Comment by avaer** [comment]
Arguably folding this hack in somewhere else is the cleaner option if we can make it work.

But since it seems this performance case is the main reason for skinned/unskinned, and it is not addressed in the PR (it is simply regressed), we should put in the plan for fixing the updates before merging anything here.

**Comment by 0reo** [comment]
based on conversation with @avaer, I'm adjusting this PR so that the setSkinning function is replaced with a toggleBoneUpdates function.  this will enable/disable matrixAutoUpdate on the bones to preserve performance when vrms are unworn, while preventing the need to remove the bones on loading of the vrm, and then creating another vrm mesh with bones once it's being worn.  This will require updating the files in webaverse app which call setSkinning, which I'll be addressing in https://github.com/webaverse/app/pull/2508.

If for some reason https://github.com/webaverse/app/pull/2508 can't/won't be addressed quickly, I can point setSkinning to the toggleBoneUpdates function, mark setSkinning as deprecated, and create another PR to remove it proper once the references in app are updated

**Comment by 0reo** [comment]
Finished toggleBoneUpdates, and went ahead and added the deprecation warning to setSkinning so this can be merged without waiting on the change in webaverse app.

**Review by avaer — APPROVED** [review]
Code looks ok.

Merging under the assumption peformance has been tested w/ a large amount of avatars and no regressions were found.

**Pull request merged**
