### PR TITLE
Pet use PhysX's `CharacterController` and raycast obstacle avoidance.

### PR DESCRIPTION
**Pull request by gonnavis**
Pet use PhysX's `CharacterController` so can react to terrain and obstacles instead of go through.

https://user-images.githubusercontent.com/10785634/150914236-2a9d88a7-0dc6-4711-8a25-a82bd0891a37.mp4

Related PR: https://github.com/webaverse/app/pull/2298

--- EDIT ---
The best solution should be using camera from pet's view to render ( low resolution ) depthTexture, then using AI to train it, instead of raycasts and hand-coded logics.

### CODE REVIEW

**Comment by gonnavis** [comment]
Added simple obstacle avoidance.
Keep trying to make it handle more complex environments, and smooth the result animations.

https://user-images.githubusercontent.com/10785634/151000844-b5fa4da5-430c-4f51-ad40-19cedada897e.mp4

**Comment by gonnavis** [comment]
Made pet can go straight onto ramp which degree less than 45deg, instead of route around.

https://user-images.githubusercontent.com/10785634/151114376-a92cbb95-c607-437d-ae7e-78dd2137892f.mp4

**Review by avaer — COMMENTED** [review]
This looks ok, but I think we will want a more general pathfinding system without these special cases.

I think the physx character controller should be able to handle the ramps.

**Comment by gonnavis** [comment]
Closed by https://github.com/webaverse/npc/pull/2
May continue the work of this PR with AI someday.

**Pull request closed without merging**
